# SPDX-License-Identifier: CC-BY-4.0
# Copyright Contributors to the Zowe project.
title: Zowe
repository: zowe/zowe.github.io
description: > # this means to ignore newlines until "keywords:"
  Zowe is an open source framework for leveraging data and applications in z/OS from modern applications and tools
keywords: mainframe, zos, open source, framework
theme: jekyll-theme-cayman
auto_ids: true

# URLs to various sites
latest_video_embed: https://www.youtube.com/embed/gje-S18-wbY
ibm_ztrial_url: https://epwt-www.mybluemix.net/software/support/trial/cst/welcomepage.wss?siteId=936&tabId=2216&w=1
github_repo_url: https://github.com/zowe
community_site_url: https://github.com/zowe/community/blob/master/README.md
forums_url: https://community.openmainframeproject.org/c/zowe
slack_url: https://slack.openmainframeproject.org
mailing_list_user_url: https://lists.openmainframeproject.org/g/zowe-user
youtube_zowe_url: https://www.youtube.com/playlist?list=PL8REpLGaY9QE_9d57tw3KQdwSVLKuTpUZ
conformance_page_url: https://www.openmainframeproject.org/projects/zowe/conformance
omp_calendar_url: https://zoom-lfx.platform.linuxfoundation.org/meetings/zowe
zos_download_url: legal.html?version=
containerization_download_url: legal.html?type=containerization&version=
cli_download_url:  legal.html?type=cli&version=
cli_plugins_download_url: legal.html?type=cli-plugins&version=
cli_active_development_download_url: legal.html?type=cli-active-development&version=
smpe_download_url: legal.html?type=smpe&version=
pswi_download_uri: legal.html?type=pswi&version=
zowe_chat_download_url: legal.html?type=chat&version=tp1

zowe_node_sdk_download_url: legal.html?type=nodejs-sdk&version=
zowe_python_sdk_download_url: legal.html?type=python-sdk&version=
nightly_build_url: https://zowe.jfrog.io/zowe/webapp/#/artifacts/browse/tree/General/libs-release-local/org/zowe/nightly
zowe_build_slack_url: https://openmainframeproject.slack.com/archives/CC9QW5NJE
lts_url: https://github.com/zowe/community/blob/master/Technical-Steering-Committee/release.md
zowe_v1_fmid: AZWE001
zowe_v1_fmid_oss_version: 1.9.0
zowe_v2_fmid: AZWE002
zowe_v2_fmid_oss_version: 2.0.0
zos_component_install_doc_url: https://docs.zowe.org/stable/user-guide/install-zos.html
zowe_containerization_install_doc_url: https://docs.zowe.org/stable/user-guide/k8s-introduction
zowe_cli_install_doc_url: https://docs.zowe.org/stable/user-guide/cli-install-cli-checklist
zowe_explorer_install_doc_url: https://docs.zowe.org/stable/user-guide/ze-install
zowe_sdk_install_doc_url: https://docs.zowe.org/stable/user-guide/sdks-using
vscode_marketplace_url: https://marketplace.visualstudio.com/items?itemName=Zowe.vscode-extension-for-zowe
zowe_docker_download_url: https://zowe.jfrog.io/zowe/libs-release-local/org/zowe
zowe_dockerhub_download_url: https://hub.docker.com/r/ompzowe/server-bundle
docker_install_doc_url: https://docs.zowe.org/stable/user-guide/install-docker.html
app_framework_doc_url: https://docs.zowe.org/stable/getting-started/overview.html#zowe-application-framework
app_framework_github_url: https://github.com/zowe/zlux
app_framework_slack_url: https://openmainframeproject.slack.com/archives/CBW5ET69G
app_framework_tour_url: https://www.youtube.com/watch?v=cbEVbcsaGCs&ab_channel=OpenMainframeProject
apiml_doc_url: https://docs.zowe.org/stable/getting-started/overview.html#api-mediation-layer
apiml_github_url: https://github.com/zowe/api-layer
apiml_slack_url: https://openmainframeproject.slack.com/archives/CC5UUL005
zowe_cli_doc_url: https://docs.zowe.org/stable/getting-started/overview.html#zowe-cli
zowe_cli_github_url: https://github.com/zowe/zowe-cli
zowe_cli_slack_url: https://openmainframeproject.slack.com/archives/CC8AALGN6
zowe_cli_secure_credential_store_plugin_url: https://github.com/zowe/zowe-cli-scs-plugin
zowe_cli_cics_plugin_url: https://github.com/zowe/zowe-cli-cics-plugin
zowe_cli_db2_plugin_url: https://github.com/zowe/zowe-cli-db2-plugin
zowe_cli_ftp_plugin_url: https://github.com/zowe/zowe-cli-ftp-plugin
zowe_cli_ims_plugin_url: https://github.com/zowe/zowe-cli-ims-plugin
zowe_cli_mq_plugin_url: https://github.com/zowe/zowe-cli-mq-plugin
zowe_explorer_doc_url: https://docs.zowe.org/stable/user-guide/ze-install.html#installing-zowe-explorer
zowe_explorer_github_url: https://github.com/zowe/zowe-explorer-vscode
zowe_explorer_slack_url: https://openmainframeproject.slack.com/archives/CUVE37Z5F
zowe_explorer_next_github_url: https://github.com/zowe/zowe-explorer-vscode/releases
zowe_explorer_next_doc_url: https://github.com/zowe/zowe-explorer-vscode/tree/next/docs/Early%20Access%20-%20Using%20Global%20Profile%20Configuration.md
zowe_cics_explorer_next_github_url: https://github.com/zowe/vscode-extension-for-cics/releases
zowe_sdk_doc_url: https://docs.zowe.org/stable/getting-started/overview.html#zowe-client-software-development-kits-sdks
zowe_sdk_github_url: https://github.com/zowe/zowe-cli
zowe_sdk_slack_url: https://openmainframeproject.slack.com/archives/C010AUS5MK5
zowe_node_sdk_url: https://github.com/zowe/zowe-cli
zowe_python_sdk_url: https://github.com/zowe/zowe-client-python-sdk
zowe_swift_sdk_url: https://github.com/zowe/zowe-client-swift-sdk
zowe_mobile_doc_url: https://docs.zowe.org/stable/getting-started/user-roadmap-zowe-mobile.html
zowe_mobile_github_url: https://github.com/zowe/zowe-on-the-go
zowe_mobile_slack_url: https://openmainframeproject.slack.com/archives/C0138CFMY74
zebra_github_url: https://github.com/zowe/zebra
zebra_doc_url: https://github.com/zowe/zebra/tree/main/Documentation
zebra_slack_url: https://openmainframeproject.slack.com/archives/C01QWBJG3A4
zebra_demo_url: https://zebra.talktothemainframe.com/
workflow_wizard_github_url: https://github.com/zowe/workflow-wizard
workflow_wizard_slack_url: https://openmainframeproject.slack.com/archives/C01T5F2RU5D
workflow_wizard_doc_url: https://github.com/zowe/workflow-wizard/raw/main/doc/Workflow%20Templates%20Reference.docx
intellij_github_url: https://github.com/zowe/zowe-explorer-intellij
intellij_slack_url: https://join.slack.com/t/iba-mainframe-tools/shared_invite/zt-pejbtt4j-l7KuizvDedJSCxwGtxmMBg
intellij_doc_url: https://plugins.jetbrains.com/plugin/18688-zowe-explorer
chat_github_url: https://github.com/zowe/zowe-chat
chat_slack_url: https://openmainframeproject.slack.com/archives/C03NNABMN0J
chat_doc_url: https://docs.zowe.org/stable/getting-started/overview#zowe-chat-technical-preview
zowe_video_deck_url: https://docs.zowe.org/Zowe_introduction_video_deck.pptx
zowe_video_transcript_url: https://docs.zowe.org/Zowe_introduction_video_script.txt
learn_page_get_started: https://docs.zowe.org/stable/getting-started/overview.html
zowe_medium_blog_url: https://medium.com/zowe
master_the_mainframe_url: https://www.ibm.com/it-infrastructure/z/education/zxplore
visual_studio_code_url: https://code.visualstudio.com/
web_dev_node_url: https://nodejs.org/
zowe_extend_doc_url: https://docs.zowe.org/stable/extend/extend-zowe-overview.html
create_zowe_issue_url: https://github.com/zowe/community/issues/new/choose
conformance_step1_url: https://www.openmainframeproject.org/projects/zowe/conformance/terms-and-conditions
conformance_step2_url: https://www.openmainframeproject.org/projects/zowe/conformance/test-evaluation-guide
conformance_step3_url: https://www.openmainframeproject.org/projects/zowe/conformance/participation-form-esign
conformance_support_step1_url: https://www.openmainframeproject.org/projects/zowe/conformance/terms-and-conditions
conformance_support_step2_url: https://www.openmainframeproject.org/projects/zowe/conformance/support-evaluation-guide
conformance_support_step3_url: https://www.openmainframeproject.org/projects/zowe/conformance/participation-form-esign
conformance_support_page_url: https://www.openmainframeproject.org/projects/zowe/conformant-support-provider
zowe_community_repo_url: https://github.com/zowe/community
zowe_zlc_repo_url: https://github.com/zowe/zlc
zowe_docs_repo_url: https://github.com/zowe/docs-site
zowe_onboarding_slack_url: https://openmainframeproject.slack.com/archives/CC60ALD61
zowe_user_slack_url: https://openmainframeproject.slack.com/archives/CC08782AG
zowe_doc_slack_url: https://openmainframeproject.slack.com/archives/CC961JYMQ
zowe_metrics_url: https://www.metrics.zowe.org/
zowe_cli_next_features_doc_url: https://github.com/zowe/zowe-cli#early-access-features
zowe_node_sdk_next_reference_doc_url: https://docs.zowe.org/stable/typedoc_next/index.html
zowe_next_release_date: 2022-04-25

# not in use, place variables here if you need to distinguish based on Zowe release
v1:
v2:

plugins:
  # Redirect plugin
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - dco_signoffs
  - .gitignore
