# SPDX-License-Identifier: CC-BY-4.0
# Copyright Contributors to the Zowe project.
theme: jekyll-theme-cayman
auto_ids: true

# URLs to various sites
latest_video_embed: https://www.youtube.com/embed/NX20ZMRoTtk
ibm_ztrial_url: https://www.openmainframeproject.org/projects/zowe/ztrial
github_repo_url: https://github.com/zowe
docs_site_url: https://zowe.github.io/docs-site/latest
community_site_url: https://github.com/zowe/community/blob/master/README.md
forums_url: https://community.openmainframeproject.org/c/zowe
slack_url: https://slack.openmainframeproject.org
mailing_list_user_url: https://lists.openmainframeproject.org/g/zowe-user
youtube_zowe_url: https://www.youtube.com/playlist?list=PL8REpLGaY9QE_9d57tw3KQdwSVLKuTpUZ
conformance_page_url: https://www.openmainframeproject.org/projects/zowe/conformance

# List of Zowe releases - update here and it will update the entire site :-)
# Note - keep this in order as the latest release is pulled from the first item in the list!
releases:
  - version: 1.4.0
    release_notes: https://zowe.github.io/docs-site/latest/getting-started/summaryofchanges.html#version-1-4-0-august-2019
    release_date: 2019-08-09
    zos_download_url: https://projectgiza.org/Downloads/legal.1.4.0.html
    cli_download_url: https://projectgiza.org/Downloads/cli.1.4.0.html
    documentation: https://zowe.github.io/docs-site/latest/
  - version: 1.3.0
    release_notes: https://zowe.github.io/docs-site/latest/getting-started/summaryofchanges.html#version-1-3-0-june-2019
    release_date: 2019-06-13
    zos_download_url: https://projectgiza.org/Downloads/legal.1.3.0.html
    cli_download_url: https://projectgiza.org/Downloads/cli.1.3.0.html
    documentation: https://zowe.github.io/docs-site/v1-3-x/
  - version: 1.2.0
    release_notes: https://zowe.github.io/docs-site/latest/getting-started/summaryofchanges.html#version-1-2-0-may-2019
    release_date: 2019-05-03
    zos_download_url: https://projectgiza.org/Downloads/legal.1.2.0.html
    cli_download_url: https://projectgiza.org/Downloads/cli.1.2.0.html
    documentation: https://zowe.github.io/docs-site/v1-2-x/
  - version: 1.1.0
    release_notes: hhttps://zowe.github.io/docs-site/latest/getting-started/summaryofchanges.html#version-1-1-0-april-2019
    release_date: 2019-04-03
    zos_download_url: https://projectgiza.org/Downloads/legal.1.1.0.html
    cli_download_url: https://projectgiza.org/Downloads/cli.1.1.0.html
    documentation: https://zowe.github.io/docs-site/v1-1-x/
  - version: 1.0.1
    release_notes: https://zowe.github.io/docs-site/latest/getting-started/summaryofchanges.html#version-1-0-1-march-2019
    release_date: 2019-03-07
    zos_download_url: https://projectgiza.org/Downloads/legal.1.0.1.html
    cli_download_url: https://projectgiza.org/Downloads/cli.1.0.1.html
    documentation: https://zowe.github.io/docs-site/v1-0-x/
  - version: 1.0.0
    release_notes: https://zowe.github.io/docs-site/latest/getting-started/summaryofchanges.html#version-1-0-0-february-2019
    release_date: 2019-02-08
    zos_download_url: https://projectgiza.org/Downloads/legal.1.0.0.html
    cli_download_url: https://projectgiza.org/Downloads/cli.1.0.0.html
    documentation: https://zowe.github.io/docs-site/v1-0-x/


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - dco_signoffs
  - .gitignore
