# SPDX-License-Identifier: CC-BY-4.0
# Copyright Contributors to the Zowe project.
title: Zowe
description: > # this means to ignore newlines until "keywords:"
  Zowe is an open source framework for leveraging data and applications in z/OS from modern applications and tools.
keywords: mainframe, zos, open source, framework
theme: jekyll-theme-cayman
auto_ids: true

# URLs to various sites
latest_video_embed: https://www.youtube.com/embed/NX20ZMRoTtk
ibm_ztrial_url: https://www.openmainframeproject.org/projects/zowe/ztrial
github_repo_url: https://github.com/zowe
docs_site_url: https://docs.zowe.org
community_site_url: https://github.com/zowe/community/blob/master/README.md
forums_url: https://community.openmainframeproject.org/c/zowe
slack_url: https://slack.openmainframeproject.org
mailing_list_user_url: https://lists.openmainframeproject.org/g/zowe-user
youtube_zowe_url: https://www.youtube.com/playlist?list=PL8REpLGaY9QE_9d57tw3KQdwSVLKuTpUZ
conformance_page_url: https://www.openmainframeproject.org/projects/zowe/conformance
zos_download_url: https://d1xozlojgf8voe.cloudfront.net/legal.html?version=
cli_download_url: https://d1xozlojgf8voe.cloudfront.net/legal.html?type=cli&version=
cli_latest_download_url: 
smpe_download_url: https://d1xozlojgf8voe.cloudfront.net/legal.html?type=smpe&version=

gems:
# Redirect plugin
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - dco_signoffs
  - .gitignore
