name: Update upcoming events

# Run this workflow 
on:
  workflow_dispatch:
  schedule:
  - cron: "0 1 * * *" # Every day at 01:00

jobs:
  # Set the job key. The key is displayed as the job name
  build:
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: zowe/zowe.github.io
          path: master

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r master/requirements.txt

      # Runs the Script to convert ics to yaml format
      - name: Run ics-to-yml.py
        run: |
          python master/assets/script/ics-to-yml.py

      - name: Check diff
        run: | #set an environment variable
          if git diff --exit-code; then
            echo "CHANGED=false" >> ${GITHUB_ENV}
          else
            echo "CHANGED=true" >> ${GITHUB_ENV}
          fi

      - name: Create pull request
        if: env.CHANGED == 'true'
        # Creates Pull Request only if there are differences
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          branch-suffix: timestamp
          path: ./master
          title: Update upcoming events
          labels: automated-build
          commit-message: Update upcoming events